import sqlite3
# BasicMapperClass.vm


import utils.sql_utils


class AcSendmailMapper :

	 # call sql #SpringForSqlBuild 387行　params 切り替え
	def addac_sendmail(MAILFROM, MAILTO, CC, BCC, SUBJECT, CONTENT, BUSINESS_UNIT, MAIL_ID, MAIL_DT, MAIL_TM, WF_CATALOG, CHARSET, USER_ID, USER_NM, PRCS_ID):
		#${method.sqlCommontString}
		params = ["MAILFROM","MAILTO","CC","BCC","SUBJECT","CONTENT","BUSINESS_UNIT","MAIL_ID","MAIL_DT","MAIL_TM","WF_CATALOG","CHARSET","USER_ID","USER_NM","PRCS_ID"]
		values = [MAILFROM, MAILTO, CC, BCC, SUBJECT, CONTENT, BUSINESS_UNIT, MAIL_ID, MAIL_DT, MAIL_TM, WF_CATALOG, CHARSET, USER_ID, USER_NM, PRCS_ID]
		return utils.sql_utils.formatSQL("""INSERT INTO WF_MAIL_QUEUE_TBL (MAILFROM, MAILTO, CC, BCC, SUBJECT, CONTENT, BUSINESS_UNIT, MAIL_ID, MAIL_DT, MAIL_TM, WF_CATALOG, CHARSET, USER_ID, USER_NM, PRCS_ID) VALUES (:MAILFROM, :MAILTO, :CC, :BCC, :SUBJECT, :CONTENT, :BUSINESS_UNIT, :MAIL_ID, :MAIL_DT, :MAIL_TM, :WF_CATALOG, :CHARSET, :USER_ID, :USER_NM, :PRCS_ID)""", params, values)

