SET global sql_mode = 'NO_ENGINE_SUBSTITUTION';
CREATE SCHEMA IF NOT EXISTS `EDISEIKYUUKANRISHISUTEMU` ;
USE EDISEIKYUUKANRISHISUTEMU;
CREATE TABLE If Not Exists `wf_sys_recfld_auto_tbl` (
  `BUSINESS_UNIT` varchar(30) NOT NULL DEFAULT '',
  `RECORD_ID` varchar(30) NOT NULL,
  `FIELD_ID` varchar(30) NOT NULL DEFAULT '',
  `NUM_VAR` varchar(50) DEFAULT NULL,
  `FIRST_REG_DTM` datetime DEFAULT NULL,
  `FIRST_REG_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_DTM` datetime DEFAULT NULL,
  `LAST_UPDATE_ID` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`BUSINESS_UNIT`,`RECORD_ID`,`FIELD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE If Not Exists `admin_user_tbl` (
  `loginid` varchar(50) NOT NULL,
  `password` varchar(250) NOT NULL,
  PRIMARY KEY (`loginid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- ----------------------------
-- Records of admin_user_tbl
-- ----------------------------
INSERT INTO `admin_user_tbl` VALUES ('admin', '7c4a8d09ca3762af61e59520943dc26494f8941b');

CREATE TABLE If Not Exists `wf_group_user_tbl` (
  `BUSINESS_UNIT` varchar(30) NOT NULL,
  `GROUP_ID` varchar(20) NOT NULL,
  `USERID` varchar(50) NOT NULL,
  `FIRST_REG_DTM` datetime DEFAULT NULL,
  `FIRST_REG_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_DTM` datetime DEFAULT NULL,
  `LAST_UPDATE_ID` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`BUSINESS_UNIT`,`GROUP_ID`,`USERID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

delete from WF_GROUP_USER_TBL where business_unit = 'EDISEIKYUUKANRISHISUTEMU';

INSERT INTO WF_GROUP_USER_TBL (BUSINESS_UNIT,GROUP_ID,USERID,FIRST_REG_DTM,FIRST_REG_ID,LAST_UPDATE_DTM,LAST_UPDATE_ID) VALUES ('EDISEIKYUUKANRISHISUTEMU','G00004','testreview001',null,'fcuser02admin',null,'fcuser02admin');

CREATE TABLE If Not Exists `wf_group_tbl` (
  `BUSINESS_UNIT` varchar(30) NOT NULL,
  `GROUP_ID` varchar(20) NOT NULL,
  `GROUP_NAME` varchar(45) NOT NULL,
  `CONTENTS` varchar(255) DEFAULT NULL,
  `FATHER_ID` varchar(20) DEFAULT NULL,
  `PATH` varchar(200) DEFAULT NULL,
  `SEQ` int(10) unsigned DEFAULT NULL,
  `LEFTID` int(10) unsigned DEFAULT NULL,
  `RIGHTID` int(10) unsigned DEFAULT NULL,
  `ENVIRONFLG` varchar(10) DEFAULT '0',
  `PAGEID` varchar(20) DEFAULT NULL,
  `GRP_FIELD1` varchar(50) DEFAULT NULL,
  `GRP_FIELD2` varchar(50) DEFAULT NULL,
  `GRP_FIELD3` varchar(50) DEFAULT NULL,
  `GRP_FIELD4` varchar(50) DEFAULT NULL,
  `GRP_FIELD5` varchar(50) DEFAULT NULL,
  `GRP_FIELD6` varchar(50) DEFAULT NULL,
  `GRP_FIELD7` varchar(50) DEFAULT NULL,
  `GRP_FIELD8` varchar(50) DEFAULT NULL,
  `GRP_FIELD9` varchar(50) DEFAULT NULL,
  `GRP_FIELD10` varchar(50) DEFAULT NULL,
  `FIRST_REG_DTM` datetime DEFAULT NULL,
  `FIRST_REG_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_DTM` datetime DEFAULT NULL,
  `LAST_UPDATE_ID` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`BUSINESS_UNIT`,`GROUP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

delete from WF_GROUP_TBL where business_unit = 'EDISEIKYUUKANRISHISUTEMU';

INSERT INTO WF_GROUP_TBL (BUSINESS_UNIT,GROUP_ID,GROUP_NAME,CONTENTS,FATHER_ID,PATH,SEQ,LEFTID,RIGHTID,ENVIRONFLG,PAGEID,GRP_FIELD1,GRP_FIELD2,GRP_FIELD3,GRP_FIELD4,GRP_FIELD5,GRP_FIELD6,GRP_FIELD7,GRP_FIELD8,GRP_FIELD9,GRP_FIELD10,FIRST_REG_DTM,FIRST_REG_ID,LAST_UPDATE_DTM,LAST_UPDATE_ID) VALUES ('EDISEIKYUUKANRISHISUTEMU','G00000','Root','Root','','.0001.','1','2','13','0',null,null,null,null,null,null,null,null,null,null,null,null,'',null,'fcuser02');
INSERT INTO WF_GROUP_TBL (BUSINESS_UNIT,GROUP_ID,GROUP_NAME,CONTENTS,FATHER_ID,PATH,SEQ,LEFTID,RIGHTID,ENVIRONFLG,PAGEID,GRP_FIELD1,GRP_FIELD2,GRP_FIELD3,GRP_FIELD4,GRP_FIELD5,GRP_FIELD6,GRP_FIELD7,GRP_FIELD8,GRP_FIELD9,GRP_FIELD10,FIRST_REG_DTM,FIRST_REG_ID,LAST_UPDATE_DTM,LAST_UPDATE_ID) VALUES ('EDISEIKYUUKANRISHISUTEMU','G00001','Root','Root','','.0002.','2','3','4','1',null,null,null,null,null,null,null,null,null,null,null,null,'',null,'fcuser02');

CREATE TABLE If Not Exists `wf_page_right_tbl` (
  `BUSINESS_UNIT` varchar(30) NOT NULL,
  `HAVINGID` varchar(41) NOT NULL,
  `PAGEID` varchar(20) NOT NULL,
  `BELONG_FLG` varchar(2) NOT NULL,
  `NORIGHTFLG` varchar(2) DEFAULT '1',
  `INSERTFLG` varchar(2) DEFAULT NULL,
  `UPDATEFLG` varchar(2) DEFAULT NULL,
  `DISPLAYFLG` varchar(2) DEFAULT NULL,
  `DELETEFLG` varchar(2) DEFAULT NULL,
  `GROUPID` varchar(20) DEFAULT NULL,
  `USERID` varchar(50) DEFAULT NULL,
  `RIGHTTYPE` varchar(1) NOT NULL DEFAULT '0',
  `ENVIRONFLG` varchar(10) NOT NULL DEFAULT '0',
  `FIRST_REG_DTM` datetime DEFAULT NULL,
  `FIRST_REG_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_DTM` datetime DEFAULT NULL,
  `LAST_UPDATE_ID` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`BUSINESS_UNIT`,`HAVINGID`,`PAGEID`,`BELONG_FLG`,`ENVIRONFLG`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

delete from WF_PAGE_RIGHT_TBL where business_unit = 'EDISEIKYUUKANRISHISUTEMU';


CREATE TABLE If Not Exists `wf_menu_tbl` (
  `BUSINESS_UNIT` varchar(30) NOT NULL DEFAULT '',
  `PROFILE_ID` varchar(20) NOT NULL,
  `FATHER_ID` varchar(20) DEFAULT NULL,
  `PFOFILE_NM` varchar(50) DEFAULT NULL,
  `CONTENTS` varchar(255) DEFAULT NULL,
  `DISPLAYFLG` varchar(2) DEFAULT '1',
  `PROFILE_TYPE` varchar(2) DEFAULT NULL,
  `PATH` varchar(200) NOT NULL,
  `SEQ` int(10) unsigned DEFAULT NULL,
  `FROMFLG` varchar(2) DEFAULT '0',
  `LEFTID` int(11) DEFAULT NULL,
  `RIGHTID` int(11) DEFAULT NULL,
  `FIRST_REG_DTM` datetime DEFAULT NULL,
  `FIRST_REG_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_DTM` datetime DEFAULT NULL,
  `LAST_UPDATE_ID` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`BUSINESS_UNIT`,`PROFILE_ID`),
  KEY `PATH` (`BUSINESS_UNIT`,`PATH`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

delete from WF_MENU_TBL where business_unit = 'EDISEIKYUUKANRISHISUTEMU';

INSERT INTO WF_MENU_TBL (BUSINESS_UNIT,PROFILE_ID,FATHER_ID,PFOFILE_NM,CONTENTS,DISPLAYFLG,PROFILE_TYPE,PATH,SEQ,FROMFLG,LEFTID,RIGHTID,FIRST_REG_DTM,FIRST_REG_ID,LAST_UPDATE_DTM,LAST_UPDATE_ID) VALUES ('EDISEIKYUUKANRISHISUTEMU','M00001','','マスター','','1','0','.0001.','1','',null,null,null,'fcuser02',null,'fcuser02');
INSERT INTO WF_MENU_TBL (BUSINESS_UNIT,PROFILE_ID,FATHER_ID,PFOFILE_NM,CONTENTS,DISPLAYFLG,PROFILE_TYPE,PATH,SEQ,FROMFLG,LEFTID,RIGHTID,FIRST_REG_DTM,FIRST_REG_ID,LAST_UPDATE_DTM,LAST_UPDATE_ID) VALUES ('EDISEIKYUUKANRISHISUTEMU','M001','M00001','会社詳細','会社詳細','1','9','.0001.0001.','1','1',null,null,null,'fcuser02',null,'fcuser02');

CREATE TABLE If Not Exists `wf_page_tbl` (
  `BUSINESS_UNIT` varchar(30) NOT NULL DEFAULT '' COMMENT 'ビジネスユニット',
  `PAGEID` varchar(20) NOT NULL COMMENT 'ページID',
  `PAGENM` varchar(45) DEFAULT NULL COMMENT 'ページ名',
  `CONTENTS` text DEFAULT NULL COMMENT '概要',
  `WF_HELP` varchar(2000) DEFAULT NULL,
  `EDITFLG` varchar(2) DEFAULT '0',
  `PC_MB_FLG` varchar(2) DEFAULT '0',
  `TRANSFLG` varchar(2) DEFAULT '0',
  `MB_WIDTH` int(10) unsigned DEFAULT NULL,
  `MB_HEIGHT` int(10) unsigned DEFAULT NULL,
  `OUTFLG` varchar(2) DEFAULT '0',
  `OURURL` varchar(255) DEFAULT NULL,
  `INSERTFLG` varchar(2) DEFAULT '1',
  `DELETEFLG` varchar(2) DEFAULT '1',
  `UPDATEFLG` varchar(2) DEFAULT '1',
  `DATACONTROLFLG` varchar(2) DEFAULT '0',
  `SEARCHTYPEFLG` varchar(2) DEFAULT NULL,
  `SEARCHMAPFLG` varchar(2) DEFAULT '0',
  `INSEXCEPTFLG` varchar(2) DEFAULT NULL,
  `INSEXCEPTPLACE` varchar(20) DEFAULT NULL,
  `UPDEXCEPTFLG` varchar(2) DEFAULT NULL,
  `UPDEXCEPTPLACE` varchar(20) DEFAULT NULL,
  `PAGE_MNG_ID` varchar(30) DEFAULT NULL,
  `USE_DEFAULT_RELATION` varchar(2) DEFAULT NULL,
  `CHECK_IN_OUT` varchar(2) DEFAULT NULL,
  `FREE_FIELD1` varchar(45) DEFAULT NULL,
  `FREE_FIELD2` varchar(45) DEFAULT NULL,
  `FREE_FIELD3` varchar(45) DEFAULT NULL,
  `FREE_FIELD4` varchar(45) DEFAULT NULL,
  `FREE_FIELD5` varchar(45) DEFAULT NULL,
  `FREE_FIELD6` varchar(45) DEFAULT NULL,
  `FREE_FIELD7` varchar(45) DEFAULT NULL,
  `FREE_FIELD8` varchar(45) DEFAULT NULL,
  `FREE_FIELD9` varchar(45) DEFAULT NULL,
  `FREE_FIELD10` varchar(45) DEFAULT NULL,
  `FIRST_REG_DTM` datetime DEFAULT NULL COMMENT '新規時間',
  `FIRST_REG_ID` varchar(50) DEFAULT NULL COMMENT '新規者ID',
  `LAST_UPDATE_DTM` datetime DEFAULT NULL COMMENT '更新時間',
  `LAST_UPDATE_ID` varchar(50) DEFAULT NULL COMMENT '更新者ID',
  PRIMARY KEY (`BUSINESS_UNIT`,`PAGEID`),
  KEY `PAGEID` (`PAGEID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

delete from WF_PAGE_TBL where business_unit = 'EDISEIKYUUKANRISHISUTEMU';

INSERT INTO WF_PAGE_TBL (BUSINESS_UNIT,PAGEID,PAGENM,CONTENTS,WF_HELP,EDITFLG,PC_MB_FLG,TRANSFLG,MB_WIDTH,MB_HEIGHT,OUTFLG,OURURL,INSERTFLG,DELETEFLG,UPDATEFLG,DATACONTROLFLG,SEARCHTYPEFLG,SEARCHMAPFLG,INSEXCEPTFLG,INSEXCEPTPLACE,UPDEXCEPTFLG,UPDEXCEPTPLACE,PAGE_MNG_ID,USE_DEFAULT_RELATION,CHECK_IN_OUT,FREE_FIELD1,FREE_FIELD2,FREE_FIELD3,FREE_FIELD4,FREE_FIELD5,FREE_FIELD6,FREE_FIELD7,FREE_FIELD8,FREE_FIELD9,FREE_FIELD10,FIRST_REG_DTM,FIRST_REG_ID,LAST_UPDATE_DTM,LAST_UPDATE_ID) VALUES ('EDISEIKYUUKANRISHISUTEMU','M001','会社詳細',null,'','1','0','0','397','90','0','','1','1','1','0','','0',null,null,null,null,'M001',null,null,null,null,null,'','1',null,null,null,null,null,null,'fcuser02',null,'fcuser02');

CREATE TABLE `wf_user_value_rel_map_tbl` (
  `BUSINESS_UNIT` varchar(30) NOT NULL,
  `RECORD_ID2` varchar(30) NOT NULL,
  `FIELD_ID2` varchar(30) NOT NULL,
  `USER_VALUE2` varchar(50) NOT NULL,
  `ENVIRONFLG` varchar(10) NOT NULL DEFAULT '0',
  `RECORD_ID1` varchar(30) DEFAULT 'wf_user_tbl',
  `USER_VALUE1` varchar(50) DEFAULT NULL,
  `RELATION` varchar(20) DEFAULT '0',
  `FIRST_REG_DTM` datetime DEFAULT NULL,
  `FIRST_REG_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_DTM` datetime DEFAULT NULL,
  `LAST_UPDATE_ID` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`BUSINESS_UNIT`,`RECORD_ID2`,`FIELD_ID2`,`USER_VALUE2`,`ENVIRONFLG`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

delete from WF_USER_VALUE_REL_MAP_TBL where business_unit = 'EDISEIKYUUKANRISHISUTEMU';


CREATE TABLE `wf_bu_attach_tbl` (
  `BUSINESS_UNIT` varchar(30) NOT NULL DEFAULT '',
  `UPLOAD_ID` varchar(50) DEFAULT NULL,
  `ATTACHID` int unsigned NOT NULL,
  `ATTACHFILENAME` varchar(250) DEFAULT NULL,
  `ATTACHFILESIZE` int unsigned DEFAULT NULL,
  `ATTACHMIMETYPE` varchar(250) DEFAULT NULL,
  `ATTACHDESC` varchar(250) DEFAULT '',
  `ATTACHCREATIONIP` varchar(20) DEFAULT NULL,
  `ATTACHCREATIONDATE` datetime DEFAULT NULL,
  `ATTACHMODIFIEDDATE` datetime DEFAULT NULL,
  `ATTACHDOWNLOADCOUNT` int unsigned DEFAULT NULL,
  `ATTACHOPTION` varchar(20) DEFAULT NULL,
  `ATTACHSTATUS` int unsigned DEFAULT NULL,
  `REFFRFORM` varchar(255) DEFAULT NULL,
  `ATTACHNEWFILENM` varchar(250) DEFAULT NULL,
  `FILETYPE` varchar(2) DEFAULT NULL,
  `THUMBIMAGENM` varchar(250) DEFAULT NULL,
  `IMAGEWIDTH` int DEFAULT '0',
  `IMAGEHEIGHT` int DEFAULT '0',
  `FIRST_REG_DTM` datetime DEFAULT NULL,
  `FIRST_REG_ID` varchar(50) DEFAULT NULL,
  `LAST_UPDATE_DTM` datetime DEFAULT NULL,
  `LAST_UPDATE_ID` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`BUSINESS_UNIT`,`ATTACHID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

delete from WF_BU_ATTACH_TBL where business_unit = 'EDISEIKYUUKANRISHISUTEMU';


