from app.dto.getmaxnumvalueentity import GetMaxNumValueEntity

class Getmaxnumvaluemapper :

	def getsysrecfldautorecordfieldauto( RECORD_ID,FIELD_ID):
		return "SELECT NUM_VAR FROM WF_SYS_RECFLD_AUTO_TBL WHERE RECORD_ID = :RECORD_ID AND FIELD_ID =:FIELD_ID"
	def insertrecordfieldautointosysrecfldauto(BUSINESS_UNIT, RECORD_ID, FIELD_ID,FIRST_REG_DTM, FIRST_REG_ID,LAST_UPDATE_DTM, LAST_UPDATE_ID):
		return "INSERT INTO WF_SYS_RECFLD_AUTO_TBL ( BUSINESS_UNIT,RECORD_ID,FIELD_ID,NUM_VAR,FIRST_REG_DTM,FIRST_REG_ID,LAST_UPDATE_DTM,LAST_UPDATE_ID) VALUES (:BUSINESS_UNIT,:RECORD_ID,:FIELD_ID,'0' ,:FIRST_REG_DTM,:FIRST_REG_ID,:LAST_UPDATE_DTM,:LAST_UPDATE_ID)"
	def uptrecordfieldautotosysrecfldauto(NUM_VAR,LAST_UPDATE_DTM,LAST_UPDATE_ID,RECORD_ID, FIELD_ID):
		return "UPDATE WF_SYS_RECFLD_AUTO_TBL SET NUM_VAR = :NUM_VAR, LAST_UPDATE_DTM = :LAST_UPDATE_DTM, LAST_UPDATE_ID = :LAST_UPDATE_ID WHERE RECORD_ID = :RECORD_ID AND FIELD_ID = :FIELD_ID"
	def getlastnumfronusertablecontent( FIELD_ID,RECORD_ID,  FIELD_IDS, headStr):
		return "SELECT MAX("+FIELD_ID+") as numString FROM "+RECORD_ID+" WHERE "+FIELD_IDS+" LIKE '"+headStr+"%'"
	


