#Mapper.vm common function mapper
import sqlite3
#Mapper.vm

import utils.sql_utils

class api118_getreportsMapper:
    def api118_getreports(role_prefecture_code,role_shokokai_cd,year_month,fy_start_month,fy_end_month,prefecture_code,shokokai_cd,form,theme,keyword):
        params = ["role_prefecture_code","role_shokokai_cd","year_month","fy_start_month","fy_end_month","prefecture_code","shokokai_cd","form","theme","keyword"]
        values = [role_prefecture_code,role_shokokai_cd,year_month,fy_start_month,fy_end_month,prefecture_code,shokokai_cd,form,theme,keyword]
        return utils.sql_utils.formatSQL("""SELECT trn_report.report_id AS report_id , trn_report.report_code AS report_code , trn_report.industry AS industry , trn_report.report_date AS report_date , trn_report.summary AS summary , trn_report.staff_main_name AS staff_main_name , trn_report.staff_sub_name AS staff_sub_name , trn_report.registered_at AS registered_at , trn_report.:prefecturecode AS prefecture_code , trn_report.:shokokaicd AS shokokai_cd , mst_prefecture.name AS prefecture_name , mst_shokokai.name AS shokokai_name , mst_:theme.label AS theme_label , mst_theme.badge_class AS theme_badge_class , mst_theme.filter_group AS theme_filter_group , mst_:form.form_code AS form_code , mst_form.short_label AS form_short_label , mst_form.badge_class AS form_badge_class FROM trn_report JOIN mst_prefecture ON mst_prefecture.prefecture_code = trn_report.prefecture_code JOIN mst_shokokai ON mst_shokokai.prefecture_code = trn_report.prefecture_code AND mst_shokokai.shokokai_cd = trn_report.shokokai_cd JOIN mst_theme ON mst_theme.theme_id = trn_report.theme_id JOIN mst_form ON mst_form.form_code = trn_report.form_code AND mst_form.fiscal_year_id = trn_report.fiscal_year_id WHERE (NULLIF(:roleprefecturecode , '' ) IS NULL OR trn_report.prefecture_code = role_prefecture_code ) AND (NULLIF(:roleshokokaicd , '' ) IS NULL OR trn_report.shokokai_cd = role_shokokai_cd ) AND (NULLIF(:yearmonth , '' ) IS NULL OR to_char(trn_report.report_date , 'YYYY-MM' ) = year_month OR (NULLIF(:fystartmonth , '' ) IS NOT NULL AND to_char(trn_report.report_date , 'YYYY-MM' ) BETWEEN fy_start_month AND :fyendmonth ) ) AND (NULLIF(prefecture_code , '' ) IS NULL OR trn_report.prefecture_code = prefecture_code ) AND (NULLIF(shokokai_cd , '' ) IS NULL OR trn_report.shokokai_cd = shokokai_cd ) AND (NULLIF(form , '' ) IS NULL OR form = '全様式' OR (form = '様式F' AND trn_report.form_code = 'F' ) OR (form = '全様式G' AND trn_report.form_code <> 'F' ) OR trn_report.form_code = form ) AND (NULLIF(theme , '' ) IS NULL OR mst_theme.filter_group = theme ) AND (NULLIF(:keyword , '' ) IS NULL OR trn_report.summary ILIKE '%' || keyword || '%' OR trn_report.staff_main_name ILIKE '%' || keyword || '%' OR trn_report.staff_sub_name ILIKE '%' || keyword || '%' ) ORDER BY trn_report.report_date DESC , trn_report.registered_at DESC;""",params,values)
