
MYSQL = "mysql"
ORACLE = "oracle"
MSSQL = "mssql"
DB2 = "db2"
HIRDB = "hirdb"
POSTGRE = "postgre"

MYSQL_DATA_TYPE_VARCHAR = "1"
MYSQL_DATA_TYPE_INT = "2"
MYSQL_DATA_TYPE_DATE = "3"
MYSQL_DATA_TYPE_UNDEFINED = "4"
MYSQL_DATA_TYPE_DOUBLE = "5"
MYSQL_DATA_TYPE_DATETIME = "6"
MYSQL_DATA_TYPE_TIME = "7"
MYSQL_DATA_TYPE_TEXT = "8"
MYSQL_DATA_TYPE_BLOB = "9"
MYSQL_DATA_TYPE_BOOLEAN = "10"

DATE_TYPE_PATTERN = "yyyy-MM-dd"
DATE_TYPE_PATTERN_SLASH = "yyyy/MM/dd"
DATETIME_TYPE_PATTERN = "yyyy/MM/dd HH:mm:ss"
TIME_TYPE_PATTERN = "HH:mm:ss"

EXPORT_DATA_TYPE_VARCHAR = "1"
EXPORT_DATA_TYPE_MONEY = "4"
EXPORT_DATA_TYPE_DATE = "3"
EXPORT_DATA_TYPE_NUMBER = "2"
EXPORT_DATA_TYPE_DATE_TIME = "5"
EXPORT_DATA_TYPE_TIME = "6"

PAGE_DB_FLG = "0"   # DB関連項目
PAGE_UNDB_FLG = "1" # 非DB項目

SQL_SORT_NULL = ""
SQL_SORT_ASC = "asc"
SQL_SORT_DESC = "desc"
