
# string_constants.py


DIVIDED_SIGN = "_-"
DIVIDED_SIGN_OF_COMMA = ","
DIVIDED_SIGN_OF_COLON = ":"
DIVIDED_SIGN_OF_SHARP = "#"
DIVIDED_SIGN_OF_SLASH = "/"
DIVIDED_SIGN_OF_QUOTES = "'"
DIVIDED_SIGN_OF_DOUBLE_QUOTES = "\""
DIVIDED_SIGN_OF_ACCENT_GRAVE = "`"
DIVIDED_SIGN_UNDERLINE = "_"
DIVIDED_SIGN_WF_COMMA = "%WF,WF%"
DIVIDED_SIGN_SPAN_SAMEDATA = "@@"

STRING_OF_LINE = "\n"
STRING_OF_BLANK = ""
STRING_OF_SPACE = " "
STRING_OF_COLON = ":"
STRING_OF_ENTER = "\n"
STRING_OF_SEMICOLON = ";"
STRING_OF_SINGLE_QUOTATION = "'"
STRING_OF_COMMA_SINGLE_QUOTATION = ",'"
STRING_OF_SINGLE_QUOTATION_COMMA = "',"
STRING_OF_DOUBLE_QUOTATION = "\""
STRING_OF_COMMA = ","
STRING_OF_AND = "AND"
STRING_OF_ASS = "の"
STRING_OF_BRACKET_LEFT = "「"
STRING_OF_BRACKET_RIGHT = "」"
STRING_OF_PUNCTUATE_MARK = "、"
STRING_OF_HYPHEN = "‐"
STRING_OF_DOLLAR = "$"
STRING_OF_PERIOD = "。"
STRING_OF_DUMY_FOR_POPFILTER = "D-1"  # Key for empty condfieldid in Popfilter table

SELECT_INIT_OPT = "<option value =''></option>"
CODE_RETURN_LINE = "\n"

STRING = "string"
INT = "int"
DATE = "date"
